springinit:
  jwt:
    issuer: yp
    secret: spring-init
    expire: 2592000000
server:
  port: 8091
  servlet:
    context-path: /api

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/spring_init
logging:
  file:
    name: 'myapp.log'
